### PR TITLE
Fix code sample image overflow

### PR DESCRIPTION
**Pull request by Arthelon**
Addresses #46

### CODE REVIEW

**Review by kiootic — COMMENTED** [review]
The image disappears when the screen width is exactly 768, can you look into it?

**Comment by Arthelon** [comment]
@kiootic This was intentional in my CSS. Mobile View for code sample wasn't clear in the designs so I asked Frank about it and he told me that there is no need for the image preview.

**Comment by kiootic** [comment]
Sorry for being unclear. The image disappears, while the space is still there:
Screenshot 2020-05-29 at 11 38 48 AM

**Comment by Arthelon** [comment]
Oh... this is an edge case with my media queries that is not limited to this component. I will need to reduce px values of all my mobile media queries by 1 to fix this.

I'll address this issue in a separate PR

**Pull request merged**
